### ISSUE TITLE
Download test data from NeuroVault is not available in "Tests/data" folder

### ISSUE THREAD

**Issue by cmaumet** [pwilliams1/nidmresults-fslhtml#13]
As discussed with @pwilliams1, if the test data is now available in the `Tests/data` folder, it should be downloaded from http://neurovault.org/collections/1692/. An example of how to use the NeuroVault APIs is available in https://github.com/incf-nidash/nidmresults-paper/blob/master/report_results.py#L35-L65.

**Comment by pwilliams1** [comment]
See #14

**Comment by cmaumet** [comment]
This was fixed in https://github.com/incf-nidash/nidmresults-fslhtml/pull/1.
