### ISSUE TITLE
Is testError.py really looking at all available NIDM-Results packs?

### ISSUE THREAD

**Issue by cmaumet** [pwilliams1/nidmresults-fslhtml#17]
Hi @pwilliams1! 

Is it correct that the following line limits the NIDM-Results packs that are downloaded form NeuroVault for the tests to only `fsl_con_f`, `fsl_thr_clustfwep05`,`ex_spm_thr_voxelunct4`,`ex_spm_thr_clustunck10`,`ex_spm_thr_voxelfdrp05`:
https://github.com/incf-nidash/nidmresults-fslhtml/blob/master/Tests/testError.py#L58
?

Could we remove this restriction and run the test against all NIDM-Results packs available at http://neurovault.org/collections/1692/?

**Comment by pwilliams1** [comment]
Ah yes, it does only run against those specific turtle files. I thought we would only need to run it on a subset of the nidm files, but I can change it to run against all of them.

**Comment by cmaumet** [comment]
That's great if you can test against all NIDM-Results in http://neurovault.org/collections/1692/ as these covers a lot of different use cases. This will ensure the viewer is robust enough to handle all those cases.

**Comment by pwilliams1** [comment]
`testError.py` now appears to be running against all turtle files (I have not pushed my changes yet) - The test has found an error with **ex_spm_partial_conjunction**, is there anything particularly different about this nidm file? I shall try and debug the error.

**Comment by cmaumet** [comment]
Yes: `ex_spm_partial_conjunction` is special in that its "Inference" activity is a `nidm_ConjunctionInference` (`nidm:NIDM_0000011`).

**Comment by pwilliams1** [comment]
I've tried looking for this in the turtle file, but can't find it. I can find a `spm_PartialConjunctionInference`

**Comment by cmaumet** [comment]
You are right!! This one is actually a partial conjunction (which is a specific type of conjunction only found in SPM) so the activity is a `spm_PartialConjunctionInference`.

**Comment by pwilliams1** [comment]
Thought so - I shall try editing the viewer to include this case.

**Comment by pwilliams1** [comment]
Good news, the above error has been solved, and `testError.py` now runs against all turtle files with no errors found.

**Comment by cmaumet** [comment]
Great! Can you refer to the commit (or PR) in a comment here and then close this issue?

**Comment by pwilliams1** [comment]
Solved in dbe11e3f10e7df8dfcb94e8c43d1adcc9f300bdc and 7de8d93c4fe585c0ee32fb44f2263a93b4a6ea05
