### ISSUE TITLE
Add support for URL specification of NIDM packs

### ISSUE THREAD

**Issue by nicholst** [pwilliams1/nidmresults-fslhtml#2]
Allow NIDM input to be specified as a URL, e.g. so that instead of just giving the NIDM pack input as `results.nidm` a full URL, like `http://neurovault.org/collections/JZRPJMWP/pain_01.nidm.zip` can be given.

**Comment by cmaumet** [comment]
@pwilliams1: you can use the `urllib2` package (cf. for example, https://github.com/incf-nidash/nidmresults-paper/blob/master/report_results.py#L55-L65).

**Comment by cmaumet** [comment]
@pwilliams1: is this also implemented in #3?

**Comment by pwilliams1** [comment]
Yes, you can run it (on command line) as follows: viewer.py urlOfNidmTurtleFile outputFolder

**Comment by cmaumet** [comment]
Fixed in #3.
