### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by cmaumet** [pwilliams1/nidmresults-fslhtml#5]
We need a set of tests to check the output of the exporter based on the nidmresults-examples data available at: https://www.nitrc.org/projects/frcl, including:
- [x] voxel-wise threshold
- [x] cluster-wise threshold
- [x] FWE-corrected threshold
- [x] FDR-corrected threshold
- [x] uncorrected voxel-wise threshold (stat value)
- [x] uncorrected voxel-wise threshold (p-value)
- [x] software (SPM or FSL)
- [x] software version

**Comment by cmaumet** [comment]
We should also test that the viewer runs without error against all the NIDM-Results packs available in :
- [x] Run a test against each available dataset and just check the viewer does not crash.

To list all NIDM-Results packs available in a folder, you can use glob as in https://github.com/incf-nidash/nidmresults-fsl/blob/master/test/test_fsl_export.py#L29.

**Comment by cmaumet** [comment]
The name of the test dataset to use for each testing variant is available in:

![](http://www.frontiersin.org/files/Articles/204386/fninf-10-00024-HTML/image_m/fninf-10-00024-t001.jpg)
Source: http://www.frontiersin.org/files/Articles/204386/fninf-10-00024-HTML/image_m/fninf-10-00024-t001.jpg

**Comment by pwilliams1** [comment]
Solved in #10
